import { api } from '../../services/studentApi';
export interface Company { _id: string; name: string; logoUrl?: string; industry?: string; website?: string; description?: string; locations?: string[]; status: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED'; createdAt: string; contact?: { name?: string; email?: string; phone?: string }; }
export interface Drive { _id: string; company: Company; role: string; jobDescription?: string; location?: string; workMode: 'ONSITE' | 'REMOTE' | 'HYBRID'; salary?: { min?: number; max?: number; currency?: string; period?: string }; batch?: { year?: number }; graduationYear?: number; eligibleCourses?: string[]; eligibleDepartments?: string[]; minimumCgpa?: number; minimumTenth?: number; minimumTwelfth?: number; maximumTotalBacklogs?: number; maximumActiveBacklogs?: number; requiredSkills?: string[]; skillMatchMode?: 'ALL' | 'ANY'; applicationDeadline?: string; status: 'DRAFT' | 'PUBLISHED' | 'CLOSED' | 'ARCHIVED'; rounds?: Array<{ name: string; type: string; order: number; durationMinutes?: number; instructions?: string }>; instructions?: string; requiredDocuments?: string[]; }
export interface PageResult<T> { items: T[]; pagination: { page: number; limit: number; total: number; pages: number }; }
export async function listCompanies(params: Record<string, string>) { return (await api.get<{ data: PageResult<Company> }>('/placement/companies', { params })).data.data; }
export async function createCompany(input: Record<string, unknown>) { return (await api.post<{ data: Company }>('/placement/companies', input)).data.data; }
export async function updateCompany(id: string, input: Record<string, unknown>) { return (await api.patch<{ data: Company }>(`/placement/companies/${id}`, input)).data.data; }
export async function updateCompanyStatus(id: string, status: Company['status']) { return (await api.patch<{ data: Company }>(`/placement/companies/${id}/status`, { status })).data.data; }
export async function listPlacementDrives(params: Record<string, string>) { return (await api.get<{ data: PageResult<Drive> }>('/placement/drives', { params })).data.data; }
export async function getPlacementDrive(id: string) { return (await api.get<{ data: Drive }>(`/placement/drives/${id}`)).data.data; }
export async function createPlacementDrive(input: Record<string, unknown>) { return (await api.post<{ data: Drive }>('/placement/drives', input)).data.data; }
export async function updatePlacementDrive(id: string, input: Record<string, unknown>) { return (await api.patch<{ data: Drive }>(`/placement/drives/${id}`, input)).data.data; }
export async function updateDriveStatus(id: string, status: 'PUBLISHED' | 'CLOSED' | 'ARCHIVED') { return (await api.patch<{ data: Drive }>(`/placement/drives/${id}/status`, { status })).data.data; }
export async function getEligibleStudents(id: string, params: Record<string, string>) { return (await api.get<{ data: PageResult<EligibleStudent> }>(`/placement/drives/${id}/eligible-students`, { params })).data.data; }
export interface EligibleStudent { _id: string; rollNumber?: string; cgpa?: number; user?: { displayName?: string; email?: string }; department?: { name?: string; code?: string }; course?: { name?: string; code?: string }; batch?: { year?: number }; }
