import { AppError } from '../lib/errors.js';
import { writeAuditLog } from '../lib/audit.js';
import { uploadPrivateFile } from '../lib/cloudinary.js';
import { Application, ApplicationStage, Attendance, Company, Document, EligibilityRule, Interview, PlacementDrive, PlacementResult, Resume, StudentProfile, User } from '../models/index.js';
import { evaluateEligibility, toEligibilityStudent, type EligibilityRules } from './eligibilityService.js';
import { allowedApplicationTransitions, isValidApplicationTransition } from './applicationWorkflow.js';

const page = (value: unknown, fallback: number) => Math.max(1, Number(value) || fallback);
const studentProfile = async (userId: string) => { const profile = await StudentProfile.findOne({ user: userId }); if (!profile) throw new AppError(404, 'Student profile not found', 'PROFILE_NOT_FOUND'); return profile; };

export async function applyToDrive(userId: string, driveId: string, resumeId?: string, actorId?: string, ipAddress?: string) {
  const profile = await studentProfile(userId); const drive = await PlacementDrive.findOne({ _id: driveId, status: 'PUBLISHED', applicationDeadline: { $gt: new Date() } }).lean(); if (!drive) throw new AppError(400, 'This placement drive is not accepting applications', 'DRIVE_NOT_OPEN');
  const rule = await (await import('../models/index.js')).EligibilityRule.findOne({ drive: driveId }).lean(); const eligibility = evaluateEligibility(toEligibilityStudent(profile.toObject()), (rule ?? drive) as never); if (!eligibility.eligible) throw new AppError(400, 'You are not eligible for this placement drive', eligibility.status);
  const resume = resumeId ? await Resume.findOne({ _id: resumeId, student: profile._id, status: 'ACTIVE' }) : await Resume.findOne({ student: profile._id, isPrimary: true, status: 'ACTIVE' }); if (!resume) throw new AppError(400, 'An active primary resume is required', 'RESUME_REQUIRED');
  try { const application = await Application.create({ student: profile._id, drive: driveId, resume: resume._id }); await ApplicationStage.create({ application: application._id, stage: 'APPLIED', changedBy: actorId ?? profile.user }); await writeAuditLog({ actorId: actorId ?? String(profile.user), action: 'APPLICATION_CREATED', entityType: 'Application', entityId: application.id, ipAddress }); return application; } catch (error) { if ((error as { code?: number }).code === 11000) throw new AppError(409, 'You have already applied to this drive', 'DUPLICATE_APPLICATION'); throw error; }
}
export async function listStudentApplications(userId: string) { const profile = await studentProfile(userId); return Application.find({ student: profile._id }).populate({ path: 'drive', populate: { path: 'company', select: 'name logoUrl industry' } }).populate('resume', 'filename').sort({ createdAt: -1 }).lean(); }
export async function getStudentApplication(userId: string, id: string) { const profile = await studentProfile(userId); const application = await Application.findOne({ _id: id, student: profile._id }).populate({ path: 'drive', populate: { path: 'company', select: 'name logoUrl industry' } }).populate('resume', 'filename').lean(); if (!application) throw new AppError(404, 'Application not found', 'APPLICATION_NOT_FOUND'); return application; }
export async function withdrawApplication(userId: string, id: string, ipAddress?: string) { const profile = await studentProfile(userId); const application = await Application.findOne({ _id: id, student: profile._id }); if (!application) throw new AppError(404, 'Application not found', 'APPLICATION_NOT_FOUND'); if (!isValidApplicationTransition(application.currentStage, 'WITHDRAWN')) throw new AppError(400, 'This application cannot be withdrawn now', 'INVALID_APPLICATION_TRANSITION'); application.currentStage = 'WITHDRAWN'; application.withdrawnAt = new Date(); await application.save(); await writeAuditLog({ actorId: userId, action: 'APPLICATION_WITHDRAWN', entityType: 'Application', entityId: id, ipAddress }); return application;
}
export async function listApplications(query: Record<string, unknown>) { const currentPage = page(query.page, 1); const limit = Math.min(100, page(query.limit, 25)); const filter: Record<string, unknown> = {}; if (query.status) filter.currentStage = query.status; if (query.student) filter.student = query.student; if (query.drive) filter.drive = query.drive; const [items, total] = await Promise.all([Application.find(filter).populate({ path: 'student', select: 'rollNumber cgpa department course batch user', populate: [{ path: 'user', select: 'displayName email' }, { path: 'department', select: 'name' }, { path: 'course', select: 'name' }] }).populate({ path: 'drive', populate: { path: 'company', select: 'name' } }).sort({ createdAt: -1 }).skip((currentPage - 1) * limit).limit(limit).lean(), Application.countDocuments(filter)]); return { items, pagination: { page: currentPage, limit, total, pages: Math.ceil(total / limit) } }; }
export async function getPlacementApplication(id: string) {
  const application = await Application.findById(id)
    .populate({ path: 'student', populate: [{ path: 'user', select: 'displayName email' }, { path: 'department', select: 'name code' }, { path: 'course', select: 'name code' }, { path: 'batch', select: 'year graduationYear' }] })
    .populate({ path: 'drive', populate: { path: 'company', select: 'name industry website locations' } })
    .populate('resume', 'filename isPrimary status uploadedAt')
    .lean();
  if (!application) throw new AppError(404, 'Application not found', 'APPLICATION_NOT_FOUND');
  const driveId = application.drive && typeof application.drive === 'object' && '_id' in application.drive ? String((application.drive as { _id: unknown })._id) : String(application.drive);
  const student = application.student && typeof application.student === 'object' ? application.student as unknown as Record<string, unknown> : undefined;
  const drive = application.drive && typeof application.drive === 'object' ? application.drive as unknown as Record<string, unknown> : undefined;
  const rule = await EligibilityRule.findOne({ drive: driveId }).lean();
  const eligibility = student ? evaluateEligibility(toEligibilityStudent(student), (rule ?? drive ?? {}) as EligibilityRules) : undefined;
  return { ...application, allowedTransitions: allowedApplicationTransitions(application.currentStage), eligibility };
}
export async function changeApplicationStatus(id: string, status: string, actorId: string, note?: string, rejectionReason?: string, ipAddress?: string) { const application = await Application.findById(id); if (!application) throw new AppError(404, 'Application not found', 'APPLICATION_NOT_FOUND'); if (!isValidApplicationTransition(application.currentStage, status)) throw new AppError(400, `Invalid application status transition from ${application.currentStage} to ${status}`, 'INVALID_APPLICATION_TRANSITION'); application.currentStage = status as typeof application.currentStage; application.reviewedAt ??= new Date(); if (status === 'SHORTLISTED') application.shortlistedAt = new Date(); if (note) application.notes = note; if (rejectionReason) application.rejectionReason = rejectionReason; await application.save(); await ApplicationStage.create({ application: application._id, stage: status, changedBy: actorId, note }); await writeAuditLog({ actorId, action: 'APPLICATION_STATUS_CHANGED', entityType: 'Application', entityId: id, metadata: { status }, ipAddress }); return getPlacementApplication(id); }

export async function scheduleInterview(input: { drive: string; application: string; selectionRoundOrder?: number; selectionRoundName?: string; type: string; date: Date; startTime?: Date; endTime?: Date; mode: 'ONLINE' | 'OFFLINE' | 'HYBRID'; venueOrLink?: string; instructions?: string }, actorId: string, ipAddress?: string) { const application = await Application.findById(input.application); if (!application || String(application.drive) !== input.drive) throw new AppError(400, 'Application does not belong to this drive', 'INVALID_APPLICATION'); const interview = await Interview.create(input); await writeAuditLog({ actorId, action: 'INTERVIEW_SCHEDULED', entityType: 'Interview', entityId: interview.id, ipAddress }); return Interview.findById(interview._id).populate({ path: 'application', populate: { path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } } }).populate({ path: 'drive', select: 'role location workMode rounds', populate: { path: 'company', select: 'name' } }).lean(); }
export async function listInterviews(userId: string, manager: boolean, query: Record<string, unknown>) { const filter: Record<string, unknown> = {}; if (!manager) { const profile = await studentProfile(userId); const applications = await Application.find({ student: profile._id }).select('_id'); filter.application = { $in: applications.map((application) => application._id) }; } if (query.drive) filter.drive = query.drive; if (query.status) filter.status = query.status; return Interview.find(filter).populate({ path: 'application', populate: { path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } } }).populate({ path: 'drive', select: 'role location workMode rounds', populate: { path: 'company', select: 'name' } }).sort({ date: 1 }).lean(); }
export async function changeInterviewStatus(id: string, status: 'SCHEDULED' | 'COMPLETED' | 'CANCELLED' | 'RESCHEDULED', actorId: string, ipAddress?: string) { const interview = await Interview.findByIdAndUpdate(id, { $set: { status } }, { new: true }); if (!interview) throw new AppError(404, 'Interview not found', 'INTERVIEW_NOT_FOUND'); await writeAuditLog({ actorId, action: 'INTERVIEW_STATUS_CHANGED', entityType: 'Interview', entityId: id, metadata: { status }, ipAddress }); return Interview.findById(id).populate({ path: 'application', populate: { path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } } }).populate({ path: 'drive', select: 'role location workMode rounds', populate: { path: 'company', select: 'name' } }).lean(); }
export async function markAttendance(interviewId: string, studentId: string, status: 'PRESENT' | 'ABSENT' | 'EXCUSED' | 'NOT_MARKED', actorId: string, remarks?: string, ipAddress?: string) { const interview = await Interview.findById(interviewId); if (!interview) throw new AppError(404, 'Interview not found', 'INTERVIEW_NOT_FOUND'); const application = await Application.findOne({ _id: interview.application, student: studentId }); if (!application) throw new AppError(400, 'Student is not assigned to this interview', 'INVALID_ATTENDANCE_STUDENT'); const attendance = await Attendance.findOneAndUpdate({ interview: interviewId, student: studentId }, { $set: { application: application._id, status, remarks, markedBy: actorId, markedAt: new Date() } }, { new: true, upsert: true, runValidators: true }); await writeAuditLog({ actorId, action: 'ATTENDANCE_MARKED', entityType: 'Attendance', entityId: attendance.id, ipAddress }); return Attendance.findById(attendance._id).populate({ path: 'interview', select: 'selectionRoundName date mode status type drive application' }).populate({ path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } }).populate('application', 'currentStage').lean(); }
export async function listAttendance(userId: string, manager: boolean, interviewId?: string) { const filter: Record<string, unknown> = {}; if (interviewId) filter.interview = interviewId; if (!manager) filter.student = (await studentProfile(userId))._id; return Attendance.find(filter).populate({ path: 'interview', select: 'selectionRoundName date mode status type drive application' }).populate({ path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } }).populate('application', 'currentStage').sort({ createdAt: -1 }).lean(); }

export async function listDocuments(userId: string, manager: boolean, studentId?: string) { const filter: Record<string, unknown> = manager ? (studentId ? { student: studentId } : {}) : { owner: userId }; const query = Document.find(filter).select('-storageKey').sort({ createdAt: -1 }); if (manager) query.populate({ path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } }); return query.lean(); }
export async function reviewDocument(id: string, status: 'PENDING' | 'VERIFIED' | 'REJECTED' | 'REUPLOAD_REQUIRED', actorId: string, reviewComment?: string, ipAddress?: string) { const document = await Document.findByIdAndUpdate(id, { $set: { status, reviewComment, reviewedBy: actorId, reviewedAt: new Date() } }, { new: true }).select('-storageKey').populate({ path: 'student', select: 'rollNumber user', populate: { path: 'user', select: 'displayName email' } }); if (!document) throw new AppError(404, 'Document not found', 'DOCUMENT_NOT_FOUND'); await writeAuditLog({ actorId, action: 'DOCUMENT_REVIEWED', entityType: 'Document', entityId: id, metadata: { status }, ipAddress }); return document; }
export async function uploadStudentDocument(userId: string, file: { buffer: Buffer; originalname: string; mimetype: string; size: number }, type: string, ipAddress?: string) { const profile = await studentProfile(userId); if (!file || file.size > 10 * 1024 * 1024) throw new AppError(400, 'Document must be under 10 MB', 'INVALID_DOCUMENT'); const allowed = ['application/pdf', 'image/jpeg', 'image/png']; if (!allowed.includes(file.mimetype)) throw new AppError(400, 'Only PDF, JPG, and PNG documents are allowed', 'INVALID_DOCUMENT'); const uploaded = await uploadPrivateFile(file.buffer, `placement-portal/documents/${userId}`, file.mimetype === 'application/pdf' ? 'raw' : 'image'); const document = await Document.create({ owner: userId, student: profile._id, type, storageKey: uploaded.publicId, secureUrl: uploaded.secureUrl, originalName: file.originalname, mimeType: file.mimetype, sizeBytes: file.size }); await writeAuditLog({ actorId: userId, action: 'DOCUMENT_UPLOADED', entityType: 'Document', entityId: document.id, ipAddress }); return document;
}
export async function createPlacementResult(input: { application: string; status: 'SELECTED' | 'NOT_SELECTED' | 'WAITLISTED'; packageCtc?: number; joiningDate?: Date; notes?: string }, actorId: string, ipAddress?: string) { const application = await Application.findById(input.application).populate('drive', 'company'); if (!application) throw new AppError(404, 'Application not found', 'APPLICATION_NOT_FOUND'); const drive = await PlacementDrive.findById(application.drive); if (!drive) throw new AppError(404, 'Placement drive not found', 'DRIVE_NOT_FOUND'); const existing = await PlacementResult.findOne({ application: application._id }); if (existing) throw new AppError(409, 'A placement result already exists for this application', 'DUPLICATE_RESULT'); const result = await PlacementResult.create({ ...input, student: application.student, application: application._id, drive: drive._id, company: drive.company, recordedBy: actorId }); await writeAuditLog({ actorId, action: 'PLACEMENT_RESULT_CREATED', entityType: 'PlacementResult', entityId: result.id, ipAddress }); return result; }
export async function listResults(userId: string, manager: boolean) { const filter = manager ? {} : { student: (await studentProfile(userId))._id }; return PlacementResult.find(filter).populate('drive', 'role').populate('company', 'name').sort({ announcedAt: -1 }).lean(); }

