import { AppError } from '../lib/errors.js';
import { writeAuditLog } from '../lib/audit.js';
import { Batch, Company, Department, EligibilityRule, PlacementDrive, StudentProfile, User } from '../models/index.js';
import { evaluateEligibility, toEligibilityStudent, type EligibilityRules } from './eligibilityService.js';

const companyName = (name: string) => name.trim().replace(/\s+/g, ' ');
const normalizedName = (name: string) => companyName(name).toLowerCase();
const page = (value: unknown, fallback: number) => Math.max(1, Number(value) || fallback);
interface DriveInput { company: string; role: string; jobDescription?: string; location?: string; workMode: 'ONSITE' | 'REMOTE' | 'HYBRID'; salary?: { min?: number; max?: number; currency?: string; period?: 'YEARLY' | 'MONTHLY' | 'HOURLY' }; batch?: string; graduationYear?: number; eligibleCourses?: string[]; eligibleDepartments?: string[]; minimumCgpa?: number; minimumTenth?: number; minimumTwelfth?: number; maximumTotalBacklogs?: number; maximumActiveBacklogs?: number; requiredSkills?: string[]; skillMatchMode?: 'ALL' | 'ANY'; applicationDeadline?: Date; rounds?: Array<Record<string, unknown>>; instructions?: string; requiredDocuments?: string[]; }

export async function listCompanies(query: { page?: unknown; limit?: unknown; search?: unknown; status?: unknown }) {
  const currentPage = page(query.page, 1); const limit = Math.min(100, page(query.limit, 20)); const filter: Record<string, unknown> = {};
  if (query.status) filter.status = query.status; else filter.status = { $ne: 'ARCHIVED' };
  if (query.search) filter.$or = [{ name: { $regex: String(query.search).slice(0, 80), $options: 'i' } }, { normalizedName: { $regex: normalizedName(String(query.search)).slice(0, 80) } }];
  const [items, total] = await Promise.all([Company.find(filter).sort({ name: 1 }).skip((currentPage - 1) * limit).limit(limit).lean(), Company.countDocuments(filter)]);
  return { items, pagination: { page: currentPage, limit, total, pages: Math.ceil(total / limit) } };
}
export async function getCompany(id: string) { const company = await Company.findById(id).lean(); if (!company) throw new AppError(404, 'Company not found', 'COMPANY_NOT_FOUND'); return company; }
export async function createCompany(input: Record<string, unknown>, actorId?: string, ipAddress?: string) { const name = companyName(String(input.name)); try { const company = await Company.create({ ...input, name, normalizedName: normalizedName(name) }); await writeAuditLog({ actorId, action: 'COMPANY_CREATED', entityType: 'Company', entityId: company.id, ipAddress }); return company; } catch (error) { if ((error as { code?: number }).code === 11000) throw new AppError(409, 'A company with this name already exists', 'DUPLICATE_COMPANY'); throw error; } }
export async function updateCompany(id: string, input: Record<string, unknown>, actorId?: string, ipAddress?: string) { const update = { ...input }; if (typeof update.name === 'string') { update.name = companyName(update.name); update.normalizedName = normalizedName(String(update.name)); } const company = await Company.findByIdAndUpdate(id, { $set: update }, { new: true, runValidators: true }).lean(); if (!company) throw new AppError(404, 'Company not found', 'COMPANY_NOT_FOUND'); await writeAuditLog({ actorId, action: 'COMPANY_UPDATED', entityType: 'Company', entityId: id, ipAddress }); return company; }
export async function setCompanyStatus(id: string, status: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED', actorId?: string, ipAddress?: string) { const company = await Company.findByIdAndUpdate(id, { $set: { status, archivedAt: status === 'ARCHIVED' ? new Date() : undefined } }, { new: true }).lean(); if (!company) throw new AppError(404, 'Company not found', 'COMPANY_NOT_FOUND'); await writeAuditLog({ actorId, action: `COMPANY_${status}`, entityType: 'Company', entityId: id, ipAddress }); return company; }

const allowedTransitions: Record<string, string[]> = { DRAFT: ['PUBLISHED', 'ARCHIVED'], PUBLISHED: ['CLOSED'], CLOSED: ['ARCHIVED'], ARCHIVED: [] };
export async function listDrives(query: { page?: unknown; limit?: unknown; status?: unknown; company?: unknown }) { const currentPage = page(query.page, 1); const limit = Math.min(100, page(query.limit, 20)); const filter: Record<string, unknown> = {}; if (query.status) filter.status = query.status; if (query.company) filter.company = query.company; const [items, total] = await Promise.all([PlacementDrive.find(filter).populate('company', 'name logoUrl industry status').sort({ applicationDeadline: 1 }).skip((currentPage - 1) * limit).limit(limit).lean(), PlacementDrive.countDocuments(filter)]); return { items, pagination: { page: currentPage, limit, total, pages: Math.ceil(total / limit) } }; }
export async function getDrive(id: string) { const drive = await PlacementDrive.findById(id).populate('company', 'name logoUrl industry status').lean(); if (!drive) throw new AppError(404, 'Placement drive not found', 'DRIVE_NOT_FOUND'); return drive; }
export async function createDrive(input: DriveInput, actorId?: string, ipAddress?: string) { const company = await Company.findOne({ _id: input.company, status: { $ne: 'ARCHIVED' } }); if (!company) throw new AppError(400, 'An active company is required', 'INVALID_COMPANY'); const deadline = input.applicationDeadline; if (deadline && Number.isNaN(deadline.valueOf())) throw new AppError(400, 'Invalid application deadline', 'INVALID_DEADLINE'); const drive = await PlacementDrive.create({ ...input, applicationDeadline: deadline }); await EligibilityRule.create({ drive: drive._id, minimumCgpa: input.minimumCgpa, departments: input.eligibleDepartments, courses: input.eligibleCourses, batches: input.batch ? [input.batch] : undefined, graduationYears: input.graduationYear ? [input.graduationYear] : undefined, minimumTenthPercentage: input.minimumTenth, minimumTwelfthPercentage: input.minimumTwelfth, maximumTotalBacklogs: input.maximumTotalBacklogs, maximumActiveBacklogs: input.maximumActiveBacklogs, requiredSkills: input.requiredSkills, skillMatchMode: input.skillMatchMode }); await writeAuditLog({ actorId, action: 'DRIVE_CREATED', entityType: 'PlacementDrive', entityId: drive.id, ipAddress }); return getDrive(drive.id); }
export async function updateDrive(id: string, input: Record<string, unknown>, actorId?: string, ipAddress?: string) { const current = await PlacementDrive.findById(id); if (!current) throw new AppError(404, 'Placement drive not found', 'DRIVE_NOT_FOUND'); if (input.status && input.status !== current.status) throw new AppError(400, 'Use the lifecycle endpoint to change drive status', 'CONTROLLED_STATUS_CHANGE'); const drive = await PlacementDrive.findByIdAndUpdate(id, { $set: input }, { new: true, runValidators: true }); const rule = await EligibilityRule.findOneAndUpdate({ drive: id }, { $set: { minimumCgpa: input.minimumCgpa, departments: input.eligibleDepartments, courses: input.eligibleCourses, batches: input.batch ? [input.batch] : undefined, graduationYears: input.graduationYear ? [input.graduationYear] : undefined, minimumTenthPercentage: input.minimumTenth, minimumTwelfthPercentage: input.minimumTwelfth, maximumTotalBacklogs: input.maximumTotalBacklogs, maximumActiveBacklogs: input.maximumActiveBacklogs, requiredSkills: input.requiredSkills, skillMatchMode: input.skillMatchMode }, $inc: { version: 1 } }, { new: true }); await writeAuditLog({ actorId, action: 'DRIVE_UPDATED', entityType: 'PlacementDrive', entityId: id, ipAddress, metadata: { eligibilityRuleVersion: rule?.version } }); return drive; }
export async function transitionDrive(id: string, status: 'PUBLISHED' | 'CLOSED' | 'ARCHIVED', actorId?: string, ipAddress?: string) { const drive = await PlacementDrive.findById(id); if (!drive) throw new AppError(404, 'Placement drive not found', 'DRIVE_NOT_FOUND'); if (!allowedTransitions[drive.status]?.includes(status)) throw new AppError(400, `Invalid drive status transition from ${drive.status} to ${status}`, 'INVALID_STATUS_TRANSITION'); if (status === 'PUBLISHED' && (!drive.applicationDeadline || drive.applicationDeadline <= new Date())) throw new AppError(400, 'A future application deadline is required before publishing', 'INVALID_DEADLINE'); drive.status = status; await drive.save(); await writeAuditLog({ actorId, action: `DRIVE_${status}`, entityType: 'PlacementDrive', entityId: id, ipAddress }); return getDrive(id); }

export async function getDriveEligibilityForStudent(driveId: string, userId: string) { const drive = await PlacementDrive.findOne({ _id: driveId, status: 'PUBLISHED' }).lean(); if (!drive) throw new AppError(404, 'Published placement drive not found', 'DRIVE_NOT_FOUND'); const profile = await StudentProfile.findOne({ user: userId }).lean(); if (!profile) throw new AppError(404, 'Student profile not found', 'PROFILE_NOT_FOUND'); const rule = await EligibilityRule.findOne({ drive: driveId }).lean(); return evaluateEligibility(toEligibilityStudent(profile), (rule ?? drive) as EligibilityRules); }
export async function listPublishedDrivesForStudent(userId: string) { const drives = await PlacementDrive.find({ status: 'PUBLISHED', applicationDeadline: { $gt: new Date() } }).populate('company', 'name logoUrl industry locations').sort({ applicationDeadline: 1 }).lean(); const ruleMap = new Map((await EligibilityRule.find({ drive: { $in: drives.map((drive) => drive._id) } }).lean()).map((rule) => [String(rule.drive), rule])); const profile = await StudentProfile.findOne({ user: userId }).lean(); if (!profile) return drives.map((drive) => ({ drive, eligibility: { eligible: false, status: 'INCOMPLETE_PROFILE', reasons: [{ rule: 'Academic Data', passed: false, message: 'Student profile is required to calculate eligibility' }], checkedAt: new Date().toISOString() } })); return drives.map((drive) => ({ drive, eligibility: evaluateEligibility(toEligibilityStudent(profile), (ruleMap.get(String(drive._id)) ?? drive) as EligibilityRules) })); }
export async function listEligibleStudents(driveId: string, query: { page?: unknown; limit?: unknown; search?: unknown }) { const drive = await PlacementDrive.findById(driveId).lean(); if (!drive) throw new AppError(404, 'Placement drive not found', 'DRIVE_NOT_FOUND'); const rule = await EligibilityRule.findOne({ drive: driveId }).lean(); const currentPage = page(query.page, 1); const limit = Math.min(100, page(query.limit, 25)); const filter: Record<string, unknown> = {}; if (query.search) filter.rollNumber = { $regex: String(query.search).slice(0, 60), $options: 'i' }; const profiles = await StudentProfile.find(filter).populate('user', 'displayName email').populate('department', 'name code').populate('course', 'name code').populate('batch', 'year').lean(); const eligible = profiles.filter((profile) => evaluateEligibility(toEligibilityStudent(profile), (rule ?? drive) as EligibilityRules).eligible); const items = eligible.slice((currentPage - 1) * limit, currentPage * limit); return { items, pagination: { page: currentPage, limit, total: eligible.length, pages: Math.ceil(eligible.length / limit) } }; }

