import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import mongoSanitize from 'express-mongo-sanitize';
import morgan from 'morgan';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/errors.js';
import { requestContext } from './middleware/request.js';
import { healthRouter } from './routes/health.js';
import { meRouter } from './routes/me.js';
import { studentRouter } from './routes/student.js';
import { placementRouter } from './routes/placement.js';

export const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.FRONTEND_ORIGIN, credentials: true, methods: ['GET', 'POST', 'PATCH', 'DELETE'] }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use(express.json({ limit: '1mb' }));
app.use(mongoSanitize());
app.use(requestContext);
app.use(morgan(':method :url :status :response-time ms'));
app.use('/health', healthRouter);
app.use('/api/v1/me', meRouter);
app.use('/api/v1/student', studentRouter);
app.use('/api/v1', placementRouter);
app.use(notFound);
app.use(errorHandler);
