import { Router } from 'express';
import multer from 'multer';
import { requireAuth } from '../middleware/auth.js';
import { requireRoles } from '../middleware/rbac.js';
import { validate } from '../lib/validation.js';
import { applyInput, attendanceInput, documentStatusInput, idInput, interviewInput, interviewStatusInput, resultInput, statusInput } from '../validators/phase4.js';
import { applicationStatus, attendance, documentStatus, documents, interviewStatus, interviews, mark, placementApplication, placementApplications, postInterview, postResult, results, studentApplication, studentApplications, uploadDocument, withdraw, apply } from '../controllers/phase4Controller.js';
const managers = requireRoles('PLACEMENT_OFFICER', 'PLACEMENT_STAFF', 'SUPER_ADMIN');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
export const phase4Router = Router();
phase4Router.post('/student/drives/:id/apply', requireAuth, requireRoles('STUDENT'), validate(applyInput), apply);
phase4Router.get('/student/applications', requireAuth, requireRoles('STUDENT'), studentApplications);
phase4Router.get('/student/applications/:id', requireAuth, requireRoles('STUDENT'), validate(idInput), studentApplication);
phase4Router.patch('/student/applications/:id/withdraw', requireAuth, requireRoles('STUDENT'), validate(idInput), withdraw);
phase4Router.get('/placement/applications', requireAuth, managers, placementApplications);
phase4Router.get('/placement/applications/:id', requireAuth, managers, validate(idInput), placementApplication);
phase4Router.patch('/placement/applications/:id/status', requireAuth, managers, validate(statusInput), applicationStatus);
phase4Router.get('/student/interviews', requireAuth, requireRoles('STUDENT'), interviews);
phase4Router.get('/placement/interviews', requireAuth, managers, interviews);
phase4Router.post('/placement/interviews', requireAuth, managers, validate(interviewInput), postInterview);
phase4Router.patch('/placement/interviews/:id/status', requireAuth, managers, validate(interviewStatusInput), interviewStatus);
phase4Router.get('/student/attendance', requireAuth, requireRoles('STUDENT'), attendance);
phase4Router.get('/placement/attendance', requireAuth, managers, attendance);
phase4Router.patch('/placement/interviews/:id/attendance', requireAuth, managers, validate(attendanceInput), mark);
phase4Router.get('/student/documents', requireAuth, requireRoles('STUDENT'), documents);
phase4Router.post('/student/documents', requireAuth, requireRoles('STUDENT'), upload.single('document'), uploadDocument);
phase4Router.get('/placement/documents', requireAuth, managers, documents);
phase4Router.patch('/placement/documents/:id/status', requireAuth, managers, validate(documentStatusInput), documentStatus);
phase4Router.get('/student/results', requireAuth, requireRoles('STUDENT'), results);
phase4Router.get('/placement/results', requireAuth, managers, results);
phase4Router.post('/placement/results', requireAuth, managers, validate(resultInput), postResult);
