import { z } from 'zod';

const id = z.string().regex(/^[a-f\d]{24}$/i);
const url = z.string().url().max(300);
const round = z.object({ name: z.string().trim().min(1).max(100), type: z.enum(['APTITUDE', 'CODING', 'TECHNICAL', 'GROUP_DISCUSSION', 'HR', 'FINAL_INTERVIEW', 'CUSTOM']), order: z.number().int().min(1).max(20), durationMinutes: z.number().int().min(1).max(600).optional(), instructions: z.string().max(2000).optional() });
export const companyInput = z.object({ body: z.object({ name: z.string().trim().min(2).max(150), logoUrl: url.optional(), industry: z.string().trim().max(100).optional(), website: url.optional(), description: z.string().trim().max(3000).optional(), locations: z.array(z.string().trim().max(100)).max(20).optional(), contact: z.object({ name: z.string().trim().max(100).optional(), email: z.string().email().optional(), phone: z.string().trim().max(25).optional() }).optional() }).strict(), params: z.record(z.string(), z.unknown()), query: z.record(z.string(), z.unknown()) });
export const companyPatch = z.object({ body: companyInput.shape.body.partial(), params: z.object({ id }), query: z.record(z.string(), z.unknown()) });
export const idOnly = z.object({ body: z.record(z.string(), z.unknown()), params: z.object({ id }), query: z.record(z.string(), z.unknown()) });
export const driveInput = z.object({ body: z.object({ company: id, role: z.string().trim().min(2).max(160), jobDescription: z.string().max(5000).optional(), location: z.string().trim().max(160).optional(), workMode: z.enum(['ONSITE', 'REMOTE', 'HYBRID']), salary: z.object({ min: z.number().min(0).optional(), max: z.number().min(0).optional(), currency: z.string().length(3).default('INR'), period: z.enum(['YEARLY', 'MONTHLY', 'HOURLY']).default('YEARLY') }).optional(), batch: id.optional(), graduationYear: z.number().int().min(2000).max(2200).optional(), eligibleCourses: z.array(id).max(50).optional(), eligibleDepartments: z.array(id).max(50).optional(), minimumCgpa: z.number().min(0).max(10).optional(), minimumTenth: z.number().min(0).max(100).optional(), minimumTwelfth: z.number().min(0).max(100).optional(), maximumTotalBacklogs: z.number().int().min(0).max(50).optional(), maximumActiveBacklogs: z.number().int().min(0).max(50).optional(), requiredSkills: z.array(z.string().trim().min(1).max(80)).max(100).optional(), skillMatchMode: z.enum(['ALL', 'ANY']).default('ALL'), applicationDeadline: z.coerce.date().optional(), rounds: z.array(round).max(20).optional(), instructions: z.string().max(3000).optional(), requiredDocuments: z.array(z.string().trim().max(100)).max(30).optional() }).strict(), params: z.record(z.string(), z.unknown()), query: z.record(z.string(), z.unknown()) });
export const drivePatch = z.object({ body: driveInput.shape.body.partial(), params: z.object({ id }), query: z.record(z.string(), z.unknown()) });
export const querySchema = z.object({ body: z.record(z.string(), z.unknown()), params: z.record(z.string(), z.unknown()), query: z.record(z.string(), z.unknown()) });
export const companyStatus = z.object({ body: z.object({ status: z.enum(['ACTIVE', 'INACTIVE', 'ARCHIVED']) }), params: z.object({ id }), query: z.record(z.string(), z.unknown()) });
export const driveStatus = z.object({ body: z.object({ status: z.enum(['PUBLISHED', 'CLOSED', 'ARCHIVED']) }), params: z.object({ id }), query: z.record(z.string(), z.unknown()) });
